runtime: nodejs18
entrypoint: node quizhub-backend/app.js

env_variables:
  MONGODB_URI: "mongodb://atlas-sql-67fb919e807b1c6d4427640b-e7kz3.a.query.mongodb.net/sample_mflix?ssl=true&authSource=admin"

handlers:
  - url: /.*
    script: auto
